### ISSUE TITLE
See first-class-lambda-lists

### ISSUE THREAD

**Issue by Hexstream** [tfeb/dsm#1]
In your documentation, you repeatedly reference the parsing of lambda lists.

So as to avoid unfortunate duplication of work, I thought I'd let you know that
[first-class-lambda-lists 1.0 will probably be completed in 2024](https://roadmap.hexstreamsoft.com/#first-class-lambda-lists).

The project is already in a relatively advanced state of completion, but is not yet usable.
Nonetheless, you may find it interesting in some way.

Hope this helps!

**Comment by tfeb** [comment]
Thank you.  I will close this issue as I think no action is needed but I've noted it diwn.

**Comment by Hexstream** [comment]
Awesome, thanks!
