### ISSUE TITLE
Bad value for optimize in bench.

### ISSUE THREAD

**Issue by Yehouda** [tfeb/dsm#3]
https://github.com/tfeb/dsm/blob/08d7f6d616174ef7c3148579dc24cf214e75cb79/bench/bench.lisp#L50
https://github.com/tfeb/dsm/blob/08d7f6d616174ef7c3148579dc24cf214e75cb79/bench/bench.lisp#L51

In both lines it pass **(speed(debug0))** as the _optimize_ argument to **make-dsb-bencher** and  **make-dsm-bencher**, which then use it to create a declaration **(optimize (speed (debug 0)))**, which is just plain wrong. 

The way **make-dsb-bencher**  and **make-dsm-bencher** are currently written it can "optimize" only one thing, e.g. **(speed  3)**, To allow it to optimize more things, an '@' character needs to be added in 
https://github.com/tfeb/dsm/blob/08d7f6d616174ef7c3148579dc24cf214e75cb79/bench/bench.lisp#L22
https://github.com/tfeb/dsm/blob/08d7f6d616174ef7c3148579dc24cf214e75cb79/bench/bench.lisp#L40

inside  **make-dsb-bencher** and **make-dsm-bencher**  so they become
``` 
`((declare (optimize ,@optimize)))
```
 and then **bench** can pass a list of optimizations like it does now.

**Comment by tfeb** [comment]
Oh, thank you, I will fix this when I'm back home.

**Comment by tfeb** [comment]
Resolved by 1c1746a I hope: thank you.
